version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
          - 27017:27017
        volumes:
          - data:/data
        environment:
          - MONGO_INITDB_ROOT_USERNAME=truser
          - MONGO_INITDB_ROOT_PASSWORD=trpass
          - MONGO_INITDB_DATABASE=trello
          - MONGO_INITDB_AUTHENTICATION_DATABASE=admin
    postgres:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=trello
        - POSTGRES_USER=truser
        - POSTGRES_PASSWORD=trpass
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
