spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trello
    username: truser
    password: trpass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      authentication-database: admin
      username: truser
      password: truser
      port: 27017
      host: localhost
      database: trello
trello:
  app:
    jwtSecret: RyI7V2Q^OuN7VahKf6gk7zUOauI+tkPn
    jwtExpirationMs: 600000
    jwtRefreshExpirationMs: 86400000